apiVersion: v1
kind: Pod
metadata:
  name: onepageapp
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: wakeup777/onepageapp
    name: onepageapp
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
      protocol: TCP

